name: app
# trunk-ignore(yamllint/quoted-strings)
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
      sdk: flutter

  go_router: ^14.0.2
  cupertino_icons: ^1.0.8
  csv: ^6.0.0
  google_maps_flutter: ^2.6.0
  http: ^1.2.1
  url_launcher: ^6.2.6
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  mocktail: ^1.0.3
  random_string: ^2.3.1
  build_runner: ^2.4.9
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/dummy_data/
    - assets/images/bus_stop/
